name: CI
on:
  push:
  pull_request:
    types: [opened, reopened, review_requested, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install thumbv7em-none-eabihf
      run: rustup target add thumbv7em-none-eabihf

    - name: Set up Rust nightly
      run: rustup component add rust-src --toolchain nightly-x86_64-unknown-linux-gnu
    
    - name: Build
      run: cargo build